# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddTeacher.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_teacher(object):
    def setupUi(self, Add_teacher):
        Add_teacher.setObjectName("Add_teacher")
        Add_teacher.resize(236, 211)
        self.lineEdit = QtWidgets.QLineEdit(Add_teacher)
        self.lineEdit.setGeometry(QtCore.QRect(20, 70, 191, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Add_teacher)
        self.label.setGeometry(QtCore.QRect(20, 40, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Add_teacher)
        self.pushButton.setGeometry(QtCore.QRect(50, 130, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Add_teacher)
        QtCore.QMetaObject.connectSlotsByName(Add_teacher)

    def retranslateUi(self, Add_teacher):
        _translate = QtCore.QCoreApplication.translate
        Add_teacher.setWindowTitle(_translate("Add_teacher", "Добавить преподавателя"))
        self.label.setText(_translate("Add_teacher", "ФИО преподавателя:"))
        self.pushButton.setText(_translate("Add_teacher", "Добавить"))
