# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(539, 492)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../okei.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Login.setWindowIcon(icon)
        self.label_icon = QtWidgets.QLabel(Login)
        self.label_icon.setGeometry(QtCore.QRect(90, 30, 351, 181))
        self.label_icon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_icon.setObjectName("label_icon")
        self.layoutWidget = QtWidgets.QWidget(Login)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 320, 439, 102))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.enter_to_account = QtWidgets.QPushButton(self.layoutWidget)
        self.enter_to_account.setMinimumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.enter_to_account.setFont(font)
        self.enter_to_account.setAutoRepeatDelay(300)
        self.enter_to_account.setObjectName("enter_to_account")
        self.horizontalLayout.addWidget(self.enter_to_account)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Учет ОКЭИ"))
        self.label_icon.setText(_translate("Login", "TextLabel"))
        self.enter_to_account.setText(_translate("Login", "Войти в аккаунт"))
